name: Build Android APK

on:
  workflow_dispatch: # Memungkinkan tombol "Run workflow" manual di GitHub
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java (JDK 17)
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: |
          cd presensi-mobile
          flutter pub get

      - name: Build APK Release
        run: |
          cd presensi-mobile
          flutter build apk --release --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: presensi-app-release
          path: presensi-mobile/build/app/outputs/flutter-apk/app-release.apk
